# Generated by Django 5.2.3 on 2025-06-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_prompt_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
