# Generated by Django 5.2.3 on 2025-06-23 08:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0007_collaboraterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
