# Generated by Django 5.2.3 on 2025-06-25 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0009_prompt_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='prompt_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
