# Generated by Django 5.2.3 on 2025-06-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0010_prompt_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='ai_generator',
            field=models.CharField(choices=[('midjourney', 'Midjourney'), ('dall-e-3', 'DALL-E 3'), ('stable-diffusion', 'Stable Diffusion'), ('adobe-firefly', 'Adobe Firefly'), ('flux', 'Flux'), ('sora', 'Sora'), ('leonardo-ai', 'Leonardo AI'), ('ideogram', 'Ideogram'), ('runwayml', 'RunwayML'), ('other', 'Other')], default='midjourney', help_text='Select the AI tool used to generate this image', max_length=50),
        ),
    ]
