# Generated by Django 5.2.3 on 2025-09-05 20:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0011_prompt_ai_generator'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='featured_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='ai_generator',
            field=models.CharField(choices=[('midjourney', 'Midjourney'), ('dall-e-3', 'DALL-E 3'), ('stable-diffusion', 'Stable Diffusion'), ('adobe-firefly', 'Adobe Firefly'), ('flux', 'Flux'), ('sora', 'Sora'), ('leonardo-ai', 'Leonardo AI'), ('ideogram', 'Ideogram'), ('runwayml', 'RunwayML'), ('other', 'Other')], default='midjourney', help_text='Select the AI tool used to generate this image/video', max_length=50),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
