# Generated by Django 5.2.3 on 2025-09-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0012_prompt_featured_video_alter_prompt_ai_generator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='video_duration',
            field=models.IntegerField(blank=True, help_text='Video duration in seconds', null=True),
        ),
    ]
