# Generated by Django 5.2.3 on 2025-09-06 19:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0014_alter_prompt_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
