# Generated by Django 5.2.3 on 2025-09-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0016_alter_prompt_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prompt',
            options={'ordering': ['order', '-created_on']},
        ),
        migrations.AddField(
            model_name='prompt',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Manual ordering position. Lower numbers appear first.'),
        ),
    ]
