# Generated by Django 5.2.3 on 2025-09-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0017_alter_prompt_options_prompt_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='order',
            field=models.FloatField(default=0.0, help_text='Manual ordering position. Lower numbers appear first.'),
        ),
    ]
