# Generated by Django 5.2.3 on 2025-10-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0019_contentflag_moderationlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationlog',
            name='service',
            field=models.CharField(choices=[('profanity', 'Custom Profanity Filter'), ('openai', 'OpenAI Moderation API'), ('cloudinary_ai', 'Cloudinary AI Vision'), ('rekognition', 'AWS Rekognition')], help_text='Which AI moderation service was used', max_length=50),
        ),
        migrations.CreateModel(
            name='ProfanityWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='Banned word or phrase (case-insensitive)', max_length=100, unique=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='How severe this word is', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to actively filter this word')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this word')),
            ],
            options={
                'ordering': ['severity', 'word'],
                'indexes': [models.Index(fields=['is_active', 'severity'], name='prompts_pro_is_acti_e62a3b_idx')],
            },
        ),
    ]
