# Generated by Django 5.2.3 on 2025-10-06 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0021_replace_rekognition_with_openai_vision'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('people-portraits', 'People & Portraits'), ('nature-landscapes', 'Nature & Landscapes'), ('architecture-structures', 'Architecture & Structures'), ('interiors-design', 'Interiors & Design'), ('fashion-beauty', 'Fashion & Beauty'), ('animals-wildlife', 'Animals & Wildlife'), ('action-movement', 'Action & Movement'), ('art-design', 'Art & Design'), ('scifi-fantasy', 'Sci-Fi & Fantasy'), ('mythology-legends', 'Mythology & Legends'), ('concept-art', 'Concept Art'), ('abstract-artistic', 'Abstract & Artistic'), ('emotions-expressions', 'Emotions & Expressions'), ('lighting-atmosphere', 'Lighting & Atmosphere'), ('seasons-events', 'Seasons & Events'), ('holidays', 'Holidays'), ('texture-detail', 'Texture & Detail'), ('magic-wonder', 'Magic & Wonder'), ('luxury-elegance', 'Luxury & Elegance'), ('humor-playful', 'Humor & Playful'), ('culture-history', 'Culture & History')], max_length=50)),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_info', to='taggit.tag')),
            ],
            options={
                'verbose_name_plural': 'Tag Categories',
                'ordering': ['category', 'tag__name'],
            },
        ),
    ]
