# Generated by Django 5.2.3 on 2025-10-11 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0023_populate_209_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this prompt was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this prompt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_prompts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prompt',
            name='deletion_reason',
            field=models.CharField(blank=True, choices=[('user', 'User Deleted'), ('orphaned_image', 'Orphaned Cloudinary File'), ('missing_image', 'Prompt Missing Image'), ('moderation', 'Content Moderation'), ('admin_manual', 'Admin Manual Delete'), ('expired_upload', 'Abandoned Upload Session')], default='user', help_text='Why was this prompt deleted?', max_length=50),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['deleted_at'], name='prompts_pro_deleted_8407cc_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['author', 'deleted_at'], name='prompts_pro_author__b8e495_idx'),
        ),
    ]
