# Generated by Django 5.2.3 on 2025-10-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0024_prompt_deleted_at_prompt_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='original_status',
            field=models.IntegerField(blank=True, help_text='Original status before soft delete (for restoration)', null=True),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['original_status'], name='prompts_pro_origina_a1b2c3_idx'),
        ),
    ]
