# Generated by Django 5.2.3 on 2025-10-13 01:48

from django.db import migrations


def create_user_profiles(apps, schema_editor):
    """
    Create UserProfile instances for all existing users who don't have one.

    This data migration ensures backward compatibility when adding the
    UserProfile model to an existing system with users.
    """
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('prompts', 'UserProfile')

    # Get all users
    users = User.objects.all()

    # Create profiles for users who don't have one
    profiles_created = 0
    for user in users:
        if not hasattr(user, 'userprofile'):
            UserProfile.objects.create(user=user)
            profiles_created += 1

    print(f"Created {profiles_created} UserProfile instances for existing users")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - delete all UserProfile instances.

    Note: This will delete all user profiles. Only use for testing.
    """
    UserProfile = apps.get_model('prompts', 'UserProfile')
    count = UserProfile.objects.count()
    UserProfile.objects.all().delete()
    print(f"Deleted {count} UserProfile instances")


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0026_userprofile_and_more'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles, reverse_migration),
    ]
