# Generated by Django 5.2.3 on 2025-10-20 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0028_userprofile_userprofile_user_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('spam', 'Spam or Misleading'), ('copyright', 'Copyright Violation'), ('harassment', 'Harassment or Bullying'), ('other', 'Other')], help_text='Primary reason for reporting', max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Additional details (optional, max 1000 characters)', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('action_taken', 'Action Taken')], default='pending', help_text='Current review status', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin review (not visible to users)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('prompt', models.ForeignKey(help_text='The prompt being reported', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='prompts.prompt')),
                ('reported_by', models.ForeignKey(help_text='User who reported this prompt', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt Report',
                'verbose_name_plural': 'Prompt Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='report_status_date_idx'), models.Index(fields=['prompt'], name='report_prompt_idx'), models.Index(fields=['reported_by'], name='report_user_idx'), models.Index(fields=['prompt', 'status'], name='report_prompt_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('prompt', 'reported_by'), name='unique_user_prompt_report')],
            },
        ),
    ]
