# Generated by Django 5.2.3 on 2025-10-21 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0029_promptreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_comments', models.BooleanField(default=True, help_text='New comments on your prompts')),
                ('notify_replies', models.BooleanField(default=True, help_text='Replies to your comments')),
                ('notify_follows', models.BooleanField(default=True, help_text='New followers')),
                ('notify_likes', models.BooleanField(default=True, help_text='Likes on your prompts')),
                ('notify_mentions', models.BooleanField(default=True, help_text='Mentions (@username)')),
                ('notify_weekly_digest', models.BooleanField(default=True, help_text='Weekly activity summary')),
                ('notify_updates', models.BooleanField(default=True, help_text='Product updates and announcements')),
                ('notify_marketing', models.BooleanField(default=False, help_text='Marketing emails and offers')),
                ('unsubscribe_token', models.CharField(blank=True, help_text='Unique token for one-click unsubscribe links', max_length=64, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When these preferences were last updated')),
                ('user', models.OneToOneField(help_text='User these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Preferences',
                'verbose_name_plural': 'Email Preferences',
                'ordering': ['user__username'],
                'indexes': [models.Index(fields=['user'], name='emailpref_user_idx'), models.Index(fields=['unsubscribe_token'], name='emailpref_token_idx')],
            },
        ),
    ]
