# Generated by Django 5.2.3 on 2025-11-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0032_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Original prompt slug for URL matching', max_length=200, unique=True)),
                ('original_title', models.CharField(help_text='Title of deleted prompt', max_length=200)),
                ('original_tags', models.JSONField(default=list, help_text='Tags from deleted prompt (for similarity matching)')),
                ('ai_generator', models.CharField(choices=[('midjourney', 'Midjourney'), ('dall-e-3', 'DALL-E 3'), ('stable-diffusion', 'Stable Diffusion'), ('adobe-firefly', 'Adobe Firefly'), ('flux', 'Flux'), ('sora', 'Sora'), ('leonardo-ai', 'Leonardo AI'), ('ideogram', 'Ideogram'), ('runwayml', 'RunwayML'), ('other', 'Other')], help_text='AI tool used for the deleted prompt', max_length=50)),
                ('likes_count', models.IntegerField(default=0, help_text='Number of likes before deletion')),
                ('redirect_to_slug', models.SlugField(blank=True, help_text='Slug of best matching prompt (for 301 redirect)', max_length=200, null=True)),
                ('redirect_similarity_score', models.FloatField(default=0.0, help_text='Similarity score 0-1 (≥0.75 = strong match)')),
                ('created_at', models.DateTimeField(help_text='When original prompt was created')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, help_text='When prompt was permanently deleted')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When to stop redirecting (90 days after deletion)')),
            ],
            options={
                'verbose_name': 'Deleted Prompt Redirect',
                'verbose_name_plural': 'Deleted Prompt Redirects',
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['slug'], name='deleted_prompt_slug_idx'), models.Index(fields=['expires_at'], name='deleted_prompt_expires_idx'), models.Index(fields=['redirect_similarity_score'], name='deleted_prompt_score_idx')],
            },
        ),
    ]
