# Generated by Django 5.2.3 on 2025-11-07 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0033_deletedprompt'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['ai_generator', 'status', 'deleted_at'], name='prompt_ai_gen_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['ai_generator', 'created_on'], name='prompt_ai_gen_date_idx'),
        ),
    ]
