# Generated by Django 5.2.3 on 2025-12-05 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0035_sitesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='trending_comment_weight',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='Points per comment (default: 5.0)', max_digits=4),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trending_gravity',
            field=models.DecimalField(decimal_places=1, default=1.5, help_text='Time decay strength - higher = faster decay (default: 1.5)', max_digits=3),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trending_like_weight',
            field=models.DecimalField(decimal_places=1, default=3.0, help_text='Points per like (default: 3.0)', max_digits=4),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trending_recency_hours',
            field=models.PositiveIntegerField(default=48, help_text="Hours to consider for 'recent' engagement velocity (default: 48)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trending_view_weight',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Points per view (default: 0.1)', max_digits=4),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='view_count_visibility',
            field=models.CharField(choices=[('admin', 'Admin Only'), ('author', 'Admin + Prompt Author'), ('premium', 'Admin + Premium Users'), ('public', 'Everyone (Public)')], default='admin', help_text='Who can see view counts on prompts', max_length=10),
        ),
        migrations.CreateModel(
            name='PromptView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', help_text='Session key for anonymous users', max_length=40)),
                ('ip_hash', models.CharField(blank=True, default='', help_text='SHA-256 hash of IP for analytics (not stored raw for privacy)', max_length=64)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='prompts.prompt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt View',
                'verbose_name_plural': 'Prompt Views',
                'indexes': [models.Index(fields=['prompt', 'viewed_at'], name='prompts_pro_prompt__99d08d_idx'), models.Index(fields=['prompt', 'user'], name='prompts_pro_prompt__37d522_idx'), models.Index(fields=['prompt', 'session_key'], name='prompts_pro_prompt__595fd0_idx')],
            },
        ),
    ]
