# Generated by Django 5.2.3 on 2025-12-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0036_sitesettings_trending_comment_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='view_rate_limit',
            field=models.PositiveIntegerField(default=10, help_text='Maximum views per minute per IP address (default: 10)'),
        ),
        migrations.AlterField(
            model_name='promptview',
            name='ip_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of IP (with pepper) for analytics', max_length=64),
        ),
    ]
