# Generated by Django 5.2.3 on 2025-12-19 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0037_add_view_rate_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Initial Upload'), ('replace', 'Replaced Avatar'), ('delete', 'Deleted Avatar'), ('delete_failed', 'Delete Failed')], max_length=20)),
                ('old_public_id', models.CharField(blank=True, help_text='Previous Cloudinary public ID', max_length=255, null=True)),
                ('new_public_id', models.CharField(blank=True, help_text='New Cloudinary public ID', max_length=255, null=True)),
                ('old_url', models.URLField(blank=True, help_text='Previous avatar URL', max_length=500, null=True)),
                ('new_url', models.URLField(blank=True, help_text='New avatar URL', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes (e.g., error messages)', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avatar Change Log',
                'verbose_name_plural': 'Avatar Change Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='avatar_log_user_idx')],
            },
        ),
    ]
