# Generated by Django 5.2.9 on 2025-12-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0039_add_collection_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='b2_image_url',
            field=models.URLField(blank=True, help_text='B2 CDN URL for original image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='b2_large_url',
            field=models.URLField(blank=True, help_text='B2 CDN URL for 1200x1200 large image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='b2_medium_url',
            field=models.URLField(blank=True, help_text='B2 CDN URL for 600x600 medium image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='b2_thumb_url',
            field=models.URLField(blank=True, help_text='B2 CDN URL for 300x300 thumbnail', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='b2_webp_url',
            field=models.URLField(blank=True, help_text='B2 CDN URL for WebP version', max_length=500, null=True),
        ),
    ]
