# Generated by Django 5.2.9 on 2025-12-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0040_add_b2_url_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='b2_video_thumb_url',
            field=models.URLField(blank=True, help_text='B2 CDN URL for video thumbnail (600x600)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='b2_video_url',
            field=models.URLField(blank=True, help_text='B2 CDN URL for original video', max_length=500, null=True),
        ),
    ]
