# Generated by Django 5.2.9 on 2026-01-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0041_add_b2_video_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='needs_seo_review',
            field=models.BooleanField(default=False, help_text='True if AI failed to generate title/tags/description'),
        ),
    ]
