# Generated by Django 5.2.9 on 2026-01-27 02:56
# Modified to properly handle unique UUID generation for existing records

import uuid
from django.db import migrations, models


def generate_unique_uuids(apps, schema_editor):
    """Generate unique UUIDs for any existing Prompt records."""
    Prompt = apps.get_model('prompts', 'Prompt')
    for prompt in Prompt.objects.all():
        prompt.processing_uuid = uuid.uuid4()
        prompt.save(update_fields=['processing_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0043_add_video_dimensions'),
    ]

    operations = [
        # Step 1: Add processing_complete field (simple boolean, no issues)
        migrations.AddField(
            model_name='prompt',
            name='processing_complete',
            field=models.BooleanField(default=False, help_text='True when AI content generation is complete'),
        ),
        # Step 2: Add processing_uuid without unique constraint first
        migrations.AddField(
            model_name='prompt',
            name='processing_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for processing page URL'),
        ),
        # Step 3: Generate unique UUIDs for existing records
        migrations.RunPython(generate_unique_uuids, migrations.RunPython.noop),
        # Step 4: Add the unique constraint
        migrations.AlterField(
            model_name='prompt',
            name='processing_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for processing page URL', unique=True),
        ),
    ]
