# Generated by Django 5.2.9 on 2026-02-04 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0044_add_processing_fields'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['status', 'created_on'], name='prompt_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['author', 'status', 'deleted_at'], name='prompt_author_status_idx'),
        ),
    ]
