# Generated by Django 5.2.9 on 2026-02-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0045_prompt_prompt_status_created_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description for AI context')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Subject Category',
                'verbose_name_plural': 'Subject Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='prompt',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Subject categories (1-3) assigned by AI', related_name='prompts', to='prompts.subjectcategory'),
        ),
    ]
