# Generated by Django 5.2.9 on 2026-02-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0047_populate_subject_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descriptor_type', models.CharField(choices=[('gender', 'Gender Presentation'), ('ethnicity', 'Ethnicity / Heritage'), ('age', 'Age Range'), ('features', 'Physical Features'), ('profession', 'Profession / Role'), ('mood', 'Mood / Atmosphere'), ('color', 'Color Palette'), ('holiday', 'Holiday / Occasion'), ('season', 'Season'), ('setting', 'Setting / Environment')], db_index=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Subject Descriptor',
                'verbose_name_plural': 'Subject Descriptors',
                'ordering': ['descriptor_type', 'name'],
                'indexes': [models.Index(fields=['descriptor_type'], name='prompts_sub_descrip_35d0df_idx')],
            },
        ),
        migrations.AddField(
            model_name='prompt',
            name='descriptors',
            field=models.ManyToManyField(blank=True, help_text='Subject descriptors (Tier 2) assigned by AI', related_name='prompts', to='prompts.subjectdescriptor'),
        ),
    ]
