# Generated by Django 5.2.9 on 2026-02-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0050_update_subject_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectdescriptor',
            name='descriptor_type',
            field=models.CharField(choices=[('gender', 'Gender Presentation'), ('ethnicity', 'Ethnicity / Heritage'), ('age', 'Age Range'), ('features', 'Physical Features'), ('profession', 'Profession / Role'), ('mood', 'Mood / Atmosphere'), ('color', 'Color Palette'), ('holiday', 'Holiday / Occasion'), ('season', 'Season'), ('setting', 'Setting / Environment')], max_length=20),
        ),
    ]
