# Generated by Django 5.2.9 on 2026-02-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0051_fix_descriptor_type_duplicate_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcategory',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
