# Generated by Django 5.2.9 on 2026-02-11 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0052_alter_subjectcategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_redirects', to='prompts.prompt')),
            ],
            options={
                'verbose_name': 'Slug Redirect',
                'verbose_name_plural': 'Slug Redirects',
                'ordering': ['-created_at'],
            },
        ),
    ]
