# Generated by Django 5.2.9 on 2026-02-12 02:27

from django.db import migrations


def rename_category(apps, schema_editor):
    SubjectCategory = apps.get_model('prompts', 'SubjectCategory')
    try:
        category = SubjectCategory.objects.get(
            name='3D Photo / Forced Perspective'
        )
        category.name = '3D Photo / Facebook 3D / Forced Perspective'
        category.slug = '3d-photo-facebook-3d-forced-perspective'
        category.save()
    except SubjectCategory.DoesNotExist:
        pass  # Category doesn't exist, nothing to rename


def reverse_rename(apps, schema_editor):
    SubjectCategory = apps.get_model('prompts', 'SubjectCategory')
    try:
        category = SubjectCategory.objects.get(
            name='3D Photo / Facebook 3D / Forced Perspective'
        )
        category.name = '3D Photo / Forced Perspective'
        category.slug = '3d-photo-forced-perspective'
        category.save()
    except SubjectCategory.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0053_add_slug_redirect'),
    ]

    operations = [
        migrations.RunPython(rename_category, reverse_rename),
    ]
