# Generated by Django 5.2.9 on 2026-02-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0054_rename_3d_photo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='seo_pass2_at',
            field=models.DateTimeField(blank=True, help_text='When the background SEO Pass 2 review last ran', null=True),
        ),
    ]
