# Generated by Django 5.2.9 on 2026-02-16 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0055_add_seo_pass2_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment_on_prompt', 'Commented on your prompt'), ('reply_to_comment', 'Replied to your comment'), ('prompt_liked', 'Liked your prompt'), ('new_follower', 'Started following you'), ('prompt_saved', 'Saved your prompt to a collection'), ('system', 'System notification')], max_length=30)),
                ('category', models.CharField(choices=[('comments', 'Comments'), ('likes', 'Likes'), ('follows', 'Follows'), ('collections', 'Collections'), ('system', 'System')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, max_length=500)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_admin_notification', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_recipient_unread'), models.Index(fields=['recipient', 'category', '-created_at'], name='notif_recipient_category'), models.Index(fields=['is_read', 'created_at'], name='notif_cleanup')],
            },
        ),
    ]
