# Generated by Django 5.2.11 on 2026-02-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0056_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Auto-expire this notification after this time',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_expired',
            field=models.BooleanField(db_index=True, default=False, help_text='Manually expired by admin'),
        ),
    ]
