# Generated by Django 5.2.11 on 2026-02-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0057_add_notification_expiry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
