# Generated by Django 5.2.11 on 2026-02-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0059_clear_system_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='batch_id',
            field=models.CharField(
                blank=True, db_index=True, default='',
                help_text='Groups notifications from the same blast',
                max_length=8,
            ),
        ),
    ]
