# Generated by Django 5.2.11 on 2026-02-27 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0060_add_notification_batch_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='openai', max_length=50)),
                ('model_name', models.CharField(default='gpt-image-1', max_length=100)),
                ('quality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('size', models.CharField(choices=[('1024x1024', 'Square (1:1)'), ('1024x1536', 'Portrait (3:4)'), ('1536x1024', 'Landscape (4:3)'), ('1792x1024', 'Wide (16:9)')], default='1024x1024', max_length=20)),
                ('images_per_prompt', models.PositiveSmallIntegerField(default=1)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('generator_category', models.CharField(default='ChatGPT', max_length=50)),
                ('reference_image_url', models.URLField(blank=True)),
                ('character_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_prompts', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('actual_cost', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_generation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_text', models.TextField()),
                ('prompt_order', models.PositiveIntegerField()),
                ('variation_number', models.PositiveSmallIntegerField(default=1)),
                ('image_url', models.URLField(blank=True)),
                ('revised_prompt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('is_selected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='prompts.bulkgenerationjob')),
                ('prompt_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_from', to='prompts.prompt')),
            ],
            options={
                'ordering': ['prompt_order', 'variation_number'],
            },
        ),
        migrations.AddIndex(
            model_name='bulkgenerationjob',
            index=models.Index(fields=['created_by', '-created_at'], name='prompts_bul_created_0a4e74_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkgenerationjob',
            index=models.Index(fields=['status'], name='prompts_bul_status_b28502_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['job', 'status'], name='prompts_gen_job_id_68ceac_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['job', 'prompt_order'], name='prompts_gen_job_id_14e26b_idx'),
        ),
    ]
