# Generated by Django 5.2.11 on 2026-02-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0061_add_bulk_generator_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
