# Generated by Django 5.2.11 on 2026-03-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0062_fix_image_url_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='source_credit',
            field=models.CharField(blank=True, help_text='Source credit text entered in bulk generator', max_length=200),
        ),
        migrations.AddField(
            model_name='prompt',
            name='source_credit',
            field=models.CharField(blank=True, help_text='Source or credit for this prompt (e.g., "PromptHero")', max_length=200),
        ),
        migrations.AddField(
            model_name='prompt',
            name='source_credit_url',
            field=models.URLField(blank=True, help_text='URL of the original source (staff-only clickable link)', max_length=500),
        ),
    ]
