# Generated by Django 5.2.11 on 2026-03-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0063_add_source_credit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkgenerationjob',
            name='api_key_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkgenerationjob',
            name='api_key_hint',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='bulkgenerationjob',
            name='size',
            field=models.CharField(choices=[('1024x1024', 'Square (1:1)'), ('1024x1536', 'Portrait (2:3)'), ('1536x1024', 'Landscape (3:2)'), ('1792x1024', 'Wide (16:9)')], default='1024x1024', max_length=20),
        ),
    ]
