# Generated by Django 5.2.11 on 2026-03-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0064_add_api_key_fields_to_bulk_generation_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkgenerationjob',
            name='size',
            field=models.CharField(choices=[('1024x1024', 'Square (1:1)'), ('1024x1536', 'Portrait (2:3)'), ('1536x1024', 'Landscape (3:2)'), ('1792x1024', 'Wide (16:9) — UNSUPPORTED (future use)')], default='1024x1024', max_length=20),
        ),
    ]
