# Generated by Django 5.2.11 on 2026-03-09 09:10

from django.db import migrations, models


def fix_generator_category(apps, schema_editor):
    """
    Backfill existing BulkGenerationJob rows that have generator_category='ChatGPT'
    (the old invalid default) to 'gpt-image-1' (the correct OpenAI model identifier).
    """
    BulkGenerationJob = apps.get_model('prompts', 'BulkGenerationJob')
    updated = BulkGenerationJob.objects.filter(
        generator_category='ChatGPT'
    ).update(generator_category='gpt-image-1')
    if updated:
        print(f"  Updated {updated} BulkGenerationJob row(s): ChatGPT -> gpt-image-1")


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0067_add_published_count_to_bulk_generation_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkgenerationjob',
            name='generator_category',
            field=models.CharField(default='gpt-image-1', max_length=50),
        ),
        migrations.RunPython(
            fix_generator_category,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
