# Generated by Django 5.2.11 on 2026-03-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0068_fix_generator_category_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='size',
            field=models.CharField(blank=True, choices=[('1024x1024', 'Square (1:1)'), ('1024x1536', 'Portrait (2:3)'), ('1536x1024', 'Landscape (3:2)'), ('1792x1024', 'Wide (16:9) — UNSUPPORTED (future use)')], default='', help_text='Per-prompt size override. Empty means job default was used.', max_length=20),
        ),
    ]
