# Generated by Django 5.2.11 on 2026-03-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0069_add_size_to_generatedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='quality',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', help_text='Per-prompt quality override. Empty means job default was used.', max_length=20),
        ),
    ]
