# Generated by Django 5.2.11 on 2026-03-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0070_add_quality_to_generatedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='target_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of images requested for this prompt group. All images in the same group share this value.'),
        ),
    ]
