# Generated by Django 5.2.11 on 2026-03-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0071_add_target_count_to_generatedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkgenerationjob',
            name='actual_total_images',
            field=models.PositiveIntegerField(default=0, help_text='True total images for this job, accounting for per-prompt count overrides. Populated at job creation. Replaces total_images property for display and progress tracking.'),
        ),
    ]
