# Generated by Django 5.2.11 on 2026-03-14 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0073_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment_on_prompt', 'Commented on your prompt'), ('reply_to_comment', 'Replied to your comment'), ('prompt_liked', 'Liked your prompt'), ('new_follower', 'Started following you'), ('prompt_saved', 'Saved your prompt to a collection'), ('system', 'System notification'), ('bulk_gen_job_completed', 'Generation job ready'), ('bulk_gen_job_failed', 'Generation job failed'), ('bulk_gen_published', 'Prompts published'), ('bulk_gen_partial', 'Prompts partially published'), ('nsfw_repeat_offender', 'Repeat NSFW offender')], max_length=30),
        ),
        migrations.CreateModel(
            name='NSFWViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(help_text='NSFW severity level that triggered this violation (critical/high).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('prompt', models.ForeignKey(blank=True, help_text='The prompt associated with this violation, if created before rejection.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nsfw_violations', to='prompts.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nsfw_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='nsfw_violation_user_recent')],
            },
        ),
    ]
