# Generated by Django 5.2.11 on 2026-03-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0074_add_nsfw_violation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsfwviolation',
            name='severity',
            field=models.CharField(choices=[('high', 'High'), ('critical', 'Critical')], help_text='NSFW severity level that triggered this violation (critical/high).', max_length=20),
        ),
    ]
