# Generated by Django 5.2.11 on 2026-03-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0075_nsfw_violation_severity_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='b2_source_image_url',
            field=models.URLField(blank=True, default='', help_text='B2 CDN URL of source image after download and re-upload (set by SRC-3)', max_length=2000),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='source_image_url',
            field=models.URLField(blank=True, default='', help_text='External URL of the source/reference image entered by the user', max_length=2000),
        ),
        migrations.AddField(
            model_name='prompt',
            name='b2_source_image_url',
            field=models.URLField(blank=True, default='', help_text='B2 CDN URL of source/reference image (admin-only display on prompt detail)', max_length=2000),
        ),
    ]
