# Generated by Django 5.2.11 on 2026-03-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0076_add_source_image_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment_on_prompt', 'Commented on your prompt'), ('reply_to_comment', 'Replied to your comment'), ('prompt_liked', 'Liked your prompt'), ('new_follower', 'Started following you'), ('prompt_saved', 'Saved your prompt to a collection'), ('system', 'System notification'), ('bulk_gen_job_completed', 'Generation job ready'), ('bulk_gen_job_failed', 'Generation job failed'), ('bulk_gen_published', 'Prompts published'), ('bulk_gen_partial', 'Prompts partially published'), ('openai_quota_alert', 'OpenAI Quota Alert'), ('nsfw_repeat_offender', 'Repeat NSFW offender')], max_length=30),
        ),
    ]
