# Generated by Django 5.2.11 on 2026-03-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0077_add_openai_quota_alert_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkgenerationjob',
            name='openai_tier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tier 1 (5 img/min)'), (2, 'Tier 2 (20 img/min)'), (3, 'Tier 3 (50 img/min)'), (4, 'Tier 4 (150 img/min)'), (5, 'Tier 5 (250 img/min)')], default=1, help_text="User's OpenAI API tier, used to set per-job concurrency and delay."),
        ),
    ]
