# Generated by Django 5.2.11 on 2026-03-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0078_add_openai_tier_to_bulkgenerationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='original_prompt_text',
            field=models.TextField(blank=True, default='', help_text='The prompt text as originally entered by the user, before any prepare-prompts modifications (translation, watermark removal, direction edits). Empty if the prompt was not modified.'),
        ),
    ]
