# Generated by Django 5.2.11 on 2026-04-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0079_add_original_prompt_text_to_generatedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkgenerationjob',
            name='generator_category',
            field=models.CharField(default='gpt-image-1.5', max_length=50),
        ),
        migrations.AlterField(
            model_name='bulkgenerationjob',
            name='model_name',
            field=models.CharField(default='gpt-image-1.5', max_length=100),
        ),
        migrations.AlterField(
            model_name='deletedprompt',
            name='ai_generator',
            field=models.CharField(choices=[('midjourney', 'Midjourney'), ('dall-e-3', 'DALL-E 3'), ('stable-diffusion', 'Stable Diffusion'), ('adobe-firefly', 'Adobe Firefly'), ('flux', 'Flux'), ('sora', 'Sora'), ('leonardo-ai', 'Leonardo AI'), ('ideogram', 'Ideogram'), ('runwayml', 'RunwayML'), ('gpt-image-1', 'GPT-Image-1'), ('gpt-image-1.5', 'GPT-Image-1.5'), ('other', 'Other')], help_text='AI tool used for the deleted prompt', max_length=50),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='ai_generator',
            field=models.CharField(choices=[('midjourney', 'Midjourney'), ('dall-e-3', 'DALL-E 3'), ('stable-diffusion', 'Stable Diffusion'), ('adobe-firefly', 'Adobe Firefly'), ('flux', 'Flux'), ('sora', 'Sora'), ('leonardo-ai', 'Leonardo AI'), ('ideogram', 'Ideogram'), ('runwayml', 'RunwayML'), ('gpt-image-1', 'GPT-Image-1'), ('gpt-image-1.5', 'GPT-Image-1.5'), ('other', 'Other')], default='midjourney', help_text='Select the AI tool used to generate this image/video', max_length=50),
        ),
    ]
