# Generated by Django 5.2.11 on 2026-04-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0080_upgrade_gpt_image_15'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='generating_started_at',
            field=models.DateTimeField(blank=True, help_text='When the image generation call was dispatched to OpenAI. Used by the job page to show accurate per-image progress on page refresh.', null=True),
        ),
    ]
