# Generated by Django 5.2.11 on 2026-04-13 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0081_add_generating_started_at_to_generated_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name shown to users, e.g. "Flux Schnell"', max_length=100)),
                ('slug', models.SlugField(help_text='URL-safe identifier, e.g. "flux-schnell"', unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description shown in model selector tooltip.')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('replicate', 'Replicate'), ('xai', 'xAI')], max_length=20)),
                ('model_identifier', models.CharField(help_text='Exact model string passed to the provider API. e.g. "black-forest-labs/flux-schnell" for Replicate, "grok-imagine-image" for xAI.', max_length=200)),
                ('credit_cost', models.PositiveSmallIntegerField(default=1, help_text='Credits consumed per image. 1 credit = 1 Flux Schnell image (~$0.003). Flux Dev = 10, Flux 1.1 Pro = 14, Nano Banana 2 = 20, Grok = 7, GPT-Image-1.5 BYOK = 2 (platform overhead only).')),
                ('available_starter', models.BooleanField(default=False, help_text='Available on free Starter tier.')),
                ('available_creator', models.BooleanField(default=False, help_text='Available on Creator tier ($9/mo).')),
                ('available_pro', models.BooleanField(default=True, help_text='Available on Pro tier ($19/mo).')),
                ('available_studio', models.BooleanField(default=True, help_text='Available on Studio tier ($49/mo).')),
                ('is_enabled', models.BooleanField(default=True, help_text='Master switch. Disabled models are hidden from all users immediately.')),
                ('is_byok_only', models.BooleanField(default=False, help_text='If True, this model only appears when the user has enabled BYOK mode. Set True for GPT-Image-1.5 (OpenAI BYOK).')),
                ('requires_platform_key', models.BooleanField(default=True, help_text='If True, uses the master platform API key from env vars (platform mode). If False + is_byok_only True, uses the user-supplied BYOK key.')),
                ('is_promotional', models.BooleanField(default=False, help_text='Shows a promotional badge in the UI (e.g. "Limited Time").')),
                ('promotional_label', models.CharField(blank=True, default='Limited Time', help_text='Badge text shown when is_promotional is True.', max_length=50)),
                ('scheduled_available_from', models.DateTimeField(blank=True, help_text='If set, model becomes enabled at this UTC datetime.', null=True)),
                ('scheduled_available_until', models.DateTimeField(blank=True, help_text='If set, model becomes disabled at this UTC datetime.', null=True)),
                ('supported_aspect_ratios', models.JSONField(default=list, help_text='List of supported aspect ratio strings for this model. Empty list means the model uses pixel-based size selection (OpenAI pattern). Replicate models use aspect ratios: ["1:1","16:9","3:2","2:3","4:5","5:4","9:16"].')),
                ('supports_quality_tiers', models.BooleanField(default=False, help_text='If True, the quality selector (Low/Med/High) is shown for this model. OpenAI GPT-Image-1.5 = True. Replicate/Flux = False.')),
                ('default_aspect_ratio', models.CharField(blank=True, default='1:1', help_text='Default aspect ratio pre-selected in the UI.', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in the model dropdown.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Generator Model',
                'verbose_name_plural': 'Generator Models',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, help_text='Current spendable credit balance.')),
                ('lifetime_earned', models.PositiveIntegerField(default=0, help_text='Total credits ever granted to this user (all time).')),
                ('monthly_allowance', models.PositiveIntegerField(default=0, help_text='Credits granted per subscription cycle. Starter=50 (one-time), Creator=250, Pro=1000, Studio=3500. 0 means no active subscription.')),
                ('allowance_resets_at', models.DateTimeField(blank=True, help_text='When the next monthly allowance top-up will be applied.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Credit',
                'verbose_name_plural': 'User Credits',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('monthly_grant', 'Monthly Grant'), ('starter_grant', 'Starter One-Time Grant'), ('topup_purchase', 'Credit Top-Up Purchase'), ('generation_spend', 'Generation Spend'), ('refund', 'Refund'), ('admin_adjustment', 'Admin Adjustment'), ('promotional_grant', 'Promotional Grant')], max_length=30)),
                ('amount', models.IntegerField(help_text='Positive = earned, negative = spent.')),
                ('balance_after', models.PositiveIntegerField(help_text='User credit balance immediately after this transaction.')),
                ('description', models.CharField(blank=True, help_text='Human-readable description, e.g. "Pro monthly grant" or "Flux Schnell x3".', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bulk_generation_job', models.ForeignKey(blank=True, help_text='The generation job that caused this spend, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='prompts.bulkgenerationjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='prompts_cre_user_id_daf8dc_idx')],
            },
        ),
    ]
