# Generated by Django 5.2.11 on 2026-04-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0082_add_generator_models_and_credit_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatormodel',
            name='supports_reference_image',
            field=models.BooleanField(default=False, help_text='If True, the Character Reference Image upload section is shown for this model. Currently only GPT-Image-1.5 (OpenAI BYOK) supports reference images. Replicate/xAI providers ignore the reference image input.'),
        ),
    ]
