# Generated by Django 5.2.11 on 2026-04-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0083_add_supports_reference_image_to_generator_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='b2_avatar_url',
            field=models.URLField(blank=True, default='', help_text='B2/Cloudflare CDN URL for avatar (replaces Cloudinary). Populated by migrate_cloudinary_to_b2 management command. Templates should check this first, fallback to Cloudinary avatar.', max_length=500),
        ),
    ]
