# Generated by Django 5.2.11 on 2026-04-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0085_drop_cloudinary_avatar_add_avatar_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default='', help_text='B2/Cloudflare CDN URL for avatar. Empty string means the user has no uploaded avatar; the letter-placeholder is rendered instead. Written by the direct-upload flow (163-C) and social-login capture (163-D).', max_length=500),
        ),
    ]
