# Generated by Django 5.2.11 on 2026-04-25 02:42
# Schema operations auto-generated by makemigrations.
# Data migration (RunPython) added manually for Session 169-B.

import django.core.validators
from django.db import migrations, models


def fix_dotted_and_misattributed_generators(apps, schema_editor):
    """
    Two corrections (Session 169-B):

    1. Retag the 7 Grok prompts that were mis-tagged
       'gpt-image-1.5' due to the hardcoded literal at
       prompts/tasks.py:3387, 3424, 3636, 3693 (pre-fix
       line numbers per 169-A diagnostic Grep E). Correct
       attribution is 'grok-imagine' — matching
       GeneratorModel.slug for provider='xai',
       model_identifier='grok-imagine-image'.

       Per 169-A Query E, all 7 dotted-ai_generator rows on
       production come from a single xAI job. Identifying
       them by joining through GeneratedImage.job is more
       precise than filtering by ai_generator alone — it
       guarantees the retag only touches rows whose source
       job genuinely was Grok.

    2. Defensive sweep: any BulkGenerationJob with a dotted
       generator_category gets dot-replaced. Per 169-A
       Query D, production has 0 such rows, but this
       catches any rows added between diagnostic and deploy.
       BulkGenerationJob.model_name is INTENTIONALLY NOT
       swept — Replicate vendor strings like
       'black-forest-labs/flux-1.1-pro' contain dots by
       design (model_name is an outbound API string, not a
       URL identifier).
    """
    Prompt = apps.get_model('prompts', 'Prompt')
    BulkGenerationJob = apps.get_model('prompts', 'BulkGenerationJob')
    GeneratedImage = apps.get_model('prompts', 'GeneratedImage')

    # Part 1: retag mis-tagged Grok prompts.
    # Identify them via their generated_from chain — these are
    # prompts whose source job used provider='xai' but whose
    # ai_generator was hardcoded to 'gpt-image-1.5'.
    grok_jobs = BulkGenerationJob.objects.filter(provider='xai')
    grok_image_pks = list(
        GeneratedImage.objects.filter(
            job__in=grok_jobs,
            prompt_page__isnull=False,
        ).values_list('prompt_page__pk', flat=True)
    )

    retag_count = Prompt.objects.filter(
        pk__in=grok_image_pks,
        ai_generator='gpt-image-1.5',
    ).update(ai_generator='grok-imagine')

    print(
        f"  [data] Retagged {retag_count} Grok prompts: "
        f"'gpt-image-1.5' -> 'grok-imagine'"
    )

    # Part 2: defensive sweep on BulkGenerationJob
    # generator_category. Expected 0 per 169-A Query D.
    from django.db.models import F, Value
    from django.db.models.functions import Replace

    dotted_count = BulkGenerationJob.objects.filter(
        generator_category__contains='.'
    ).count()
    if dotted_count > 0:
        BulkGenerationJob.objects.filter(
            generator_category__contains='.'
        ).update(
            generator_category=Replace(
                F('generator_category'),
                Value('.'),
                Value('-'),
            )
        )
    print(
        f"  [data] BulkGenerationJob generator_category "
        f"dotted rows fixed: {dotted_count}"
    )


def reverse_fix(apps, schema_editor):
    """
    Reverse migration (Session 169-B).

    Reverts the 7 Grok prompt retags to the original
    incorrect value 'gpt-image-1.5'. There is no correct
    dotted form of this data — the original value was
    misattributed AND dotted; the reverse exists only for
    rollback safety. Production should never invoke this.

    The defensive sweep on BulkGenerationJob.generator_category
    is NOT reversed — we don't know which specific rows had
    dots before the forward pass, so any 'reverse' would
    over-touch rows that were already dot-free pre-forward.
    Acceptable: production has 0 such rows per Query D, so
    the forward sweep is a no-op in practice.
    """
    Prompt = apps.get_model('prompts', 'Prompt')
    BulkGenerationJob = apps.get_model('prompts', 'BulkGenerationJob')
    GeneratedImage = apps.get_model('prompts', 'GeneratedImage')

    grok_jobs = BulkGenerationJob.objects.filter(provider='xai')
    grok_image_pks = list(
        GeneratedImage.objects.filter(
            job__in=grok_jobs,
            prompt_page__isnull=False,
        ).values_list('prompt_page__pk', flat=True)
    )

    reverted = Prompt.objects.filter(
        pk__in=grok_image_pks,
        ai_generator='grok-imagine',
    ).update(ai_generator='gpt-image-1.5')

    print(
        f"  [data] REVERSE: reverted {reverted} prompts to "
        f"'gpt-image-1.5' (rollback only)"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0086_alter_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkgenerationjob',
            name='generator_category',
            field=models.CharField(default='gpt-image-1-5', max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_generator_slug', message='Generator slug must contain only lowercase letters, digits, and dashes (no dots, underscores, slashes, or whitespace). Display names live separately.', regex='^[a-z0-9][a-z0-9-]*$|^$')]),
        ),
        migrations.AlterField(
            model_name='bulkgenerationjob',
            name='model_name',
            field=models.CharField(default='gpt-image-1-5', max_length=100),
        ),
        migrations.AlterField(
            model_name='deletedprompt',
            name='ai_generator',
            field=models.CharField(choices=[('midjourney', 'Midjourney'), ('dall-e-3', 'DALL-E 3'), ('stable-diffusion', 'Stable Diffusion'), ('adobe-firefly', 'Adobe Firefly'), ('flux', 'Flux'), ('sora', 'Sora'), ('leonardo-ai', 'Leonardo AI'), ('ideogram', 'Ideogram'), ('runwayml', 'RunwayML'), ('gpt-image-1', 'GPT-Image-1'), ('gpt-image-1-5', 'GPT-Image-1.5'), ('gpt-image-1-5-byok', 'GPT-Image-1.5 (BYOK)'), ('flux-schnell', 'Flux Schnell'), ('flux-dev', 'Flux Dev'), ('flux-1-1-pro', 'Flux 1.1 Pro'), ('flux-2-pro', 'FLUX 2 Pro'), ('grok-imagine', 'Grok Imagine'), ('nano-banana-2', 'Nano Banana 2'), ('other', 'Other')], help_text='AI tool used for the deleted prompt', max_length=50),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='ai_generator',
            field=models.CharField(choices=[('midjourney', 'Midjourney'), ('dall-e-3', 'DALL-E 3'), ('stable-diffusion', 'Stable Diffusion'), ('adobe-firefly', 'Adobe Firefly'), ('flux', 'Flux'), ('sora', 'Sora'), ('leonardo-ai', 'Leonardo AI'), ('ideogram', 'Ideogram'), ('runwayml', 'RunwayML'), ('gpt-image-1', 'GPT-Image-1'), ('gpt-image-1-5', 'GPT-Image-1.5'), ('gpt-image-1-5-byok', 'GPT-Image-1.5 (BYOK)'), ('flux-schnell', 'Flux Schnell'), ('flux-dev', 'Flux Dev'), ('flux-1-1-pro', 'Flux 1.1 Pro'), ('flux-2-pro', 'FLUX 2 Pro'), ('grok-imagine', 'Grok Imagine'), ('nano-banana-2', 'Nano Banana 2'), ('other', 'Other')], default='midjourney', help_text='Select the AI tool used to generate this image/video', max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_generator_slug', message='Generator slug must contain only lowercase letters, digits, and dashes (no dots, underscores, slashes, or whitespace). Display names live separately.', regex='^[a-z0-9][a-z0-9-]*$|^$')]),
        ),
        migrations.RunPython(
            fix_dotted_and_misattributed_generators,
            reverse_code=reverse_fix,
        ),
    ]
