# Generated by Django 5.2.11 on 2026-04-25 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0087_add_generator_slug_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedprompt',
            name='ai_generator',
            field=models.CharField(choices=[('midjourney', 'Midjourney'), ('dall-e-3', 'DALL-E 3'), ('stable-diffusion', 'Stable Diffusion'), ('adobe-firefly', 'Adobe Firefly'), ('flux', 'Flux'), ('sora', 'Sora'), ('leonardo-ai', 'Leonardo AI'), ('ideogram', 'Ideogram'), ('runwayml', 'RunwayML'), ('gpt-image-1', 'GPT-Image-1'), ('gpt-image-1-5', 'GPT-Image-1.5'), ('gpt-image-1-5-byok', 'GPT-Image-1.5 (BYOK)'), ('flux-schnell', 'Flux Schnell'), ('flux-dev', 'Flux Dev'), ('flux-1-1-pro', 'Flux 1.1 Pro'), ('flux-2-pro', 'FLUX 2 Pro'), ('grok-imagine', 'Grok Imagine'), ('nano-banana-2', 'Nano Banana 2'), ('other', 'Other')], help_text='AI tool used for the deleted prompt', max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_generator_slug', message='Generator slug must contain only lowercase letters, digits, and dashes (no dots, underscores, slashes, or whitespace). Display names live separately.', regex='^[a-z0-9][a-z0-9-]*$|^$')]),
        ),
    ]
