# Generated by Django 5.2.11 on 2026-04-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0088_add_deletedprompt_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='error_type',
            field=models.CharField(blank=True, choices=[('', ''), ('auth', 'Auth'), ('rate_limit', 'Rate limit'), ('content_policy', 'Content policy'), ('quota', 'Quota'), ('invalid_request', 'Invalid request'), ('server_error', 'Server error'), ('unknown', 'Unknown')], default='', help_text='Structured error category from the provider. Mirrors GenerationResult.error_type. Empty when image is not failed.', max_length=20),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of retry attempts consumed by _run_generation_with_retry before this image reached its current state. 0 if no retries occurred.'),
        ),
    ]
