# Generated by Django 5.2.11 on 2026-05-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0091_add_gpt_image_2_to_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='profanityword',
            name='affected_providers',
            field=models.JSONField(blank=True, default=list, help_text="List of provider+model identifiers this word triggers. Only consulted when block_scope='provider_advisory'. Format: model identifier strings matching the seed file's model_identifier values, e.g. ['gpt-image-1.5', 'gpt-image-2', 'google/nano-banana-2', 'grok-imagine-image']. Empty list with block_scope='provider_advisory' = no enforcement (warn-only)."),
        ),
        migrations.AddField(
            model_name='profanityword',
            name='block_scope',
            field=models.CharField(choices=[('universal', 'Universal — blocks across all providers'), ('provider_advisory', 'Provider advisory — only blocks for selected providers')], default='universal', help_text="Universal: blocks across all providers (legacy behavior — all pre-173-B words default to this). Provider advisory: only blocks when the user has selected one of the providers in 'affected_providers' below.", max_length=20),
        ),
        migrations.AddField(
            model_name='profanityword',
            name='last_reviewed_at',
            field=models.DateField(blank=True, help_text="Date this word's classification was last manually reviewed. Provider policies drift over time; entries older than 90 days warrant review. Surfaced in admin list view.", null=True),
        ),
        migrations.AddField(
            model_name='profanityword',
            name='review_notes',
            field=models.TextField(blank=True, default='', help_text='Free-text notes on classification rationale, examples of false positives observed, or links to provider documentation. Internal-only.'),
        ),
    ]
