"""
Prompt admin classes for the prompts app.

Extracted from prompts/admin.py in Session 168-F.

Contains:
- PromptAdmin (the main 950-LOC PromptAdmin with custom URLs and SEO actions)
- PromptViewAdmin (read-only analytics)
- SlugRedirectAdmin (slug redirect manager)
"""
import logging

from django.contrib import admin
from django.urls import reverse
from django.utils.html import format_html
from django_summernote.admin import SummernoteModelAdmin

from prompts.models import Prompt, PromptView, SlugRedirect
from prompts.utils.related import (
    W_TAG, W_CATEGORY, W_DESCRIPTOR, W_GENERATOR, W_ENGAGEMENT, W_RECENCY,
)

from .forms import PromptAdminForm
from .inlines import SlugRedirectInline


logger = logging.getLogger(__name__)


@admin.register(Prompt)
class PromptAdmin(SummernoteModelAdmin):
    form = PromptAdminForm
    inlines = [SlugRedirectInline]
    list_display = (
        'title', 'order', 'slug', 'status', 'moderation_badge', 'created_on',
        'author', 'tag_list', 'category_count', 'descriptor_count',
        'number_of_likes', 'ai_generator', 'media_type',
        'deleted_at', 'image_validation', 'reorder_links', 'processing_complete',
    )
    list_display_links = ('title',)
    search_fields = ['title', 'content', 'slug', 'tags__name',
                     'categories__name', 'descriptors__name', 'author__username']
    list_filter = (
        'status', 'moderation_status', 'requires_manual_review',
        'deleted_at', 'created_on', 'ai_generator', 'categories',
    )
    summernote_fields = ('content',)
    filter_horizontal = ('categories', 'descriptors')
    ordering = ['order', '-created_on']
    # Order matters: most important/common actions first
    actions = ['approve_and_publish', 'make_published', 'make_draft', 'reset_order_to_date', 'run_seo_review', 'regenerate_ai_content']
    list_editable = ('order',)
    list_per_page = 50  # Pagination for performance
    date_hierarchy = 'created_on'

    fieldsets = (
        ('Content', {
            'fields': ('id', 'title', 'slug', 'content', 'excerpt'),
            'description': (
                '⚠️ Changing the slug auto-creates a 301 redirect from the old URL. '
                '📏 Title: 10-80 chars for best SEO performance.'
            ),
        }),
        ('AI-Generated Metadata', {
            'fields': ('categories', 'descriptors', 'tags'),
            'description': (
                '🤖 Auto-generated by AI during upload. Edit to correct mistakes. '
                f'📊 Scoring weights: '
                f'descriptors {int(W_DESCRIPTOR * 100)}%, '
                f'tags {int(W_TAG * 100)}%, '
                f'categories {int(W_CATEGORY * 100)}%, '
                f'generator {int(W_GENERATOR * 100)}%, '
                f'engagement {int(W_ENGAGEMENT * 100)}%, '
                f'recency {int(W_RECENCY * 100)}%.'
            ),
        }),
        ('Media', {
            'fields': ('featured_image', 'featured_video', 'video_duration'),
            'description': (
                'Upload either an image OR a video, not both. '
                '⚠️ Title/slug changes do NOT update stored B2 filenames or alt tags.'
            ),
        }),
        ('Media Preview', {
            'fields': ('media_preview_display',),
        }),
        ('B2 Media URLs', {
            'fields': (
                'b2_image_url', 'b2_thumb_url', 'b2_medium_url',
                'b2_large_url', 'b2_webp_url',
                'b2_video_url', 'b2_video_thumb_url',
                'video_width', 'video_height',
            ),
            'description': (
                'B2/Cloudflare CDN URLs — read only, for debugging. '
                'Image prompts use b2_image/thumb/medium/large/webp. '
                'Video prompts only have b2_video_url and b2_video_thumb_url '
                '(image fields will be empty — this is normal).'
            ),
        }),
        ('Publishing', {
            'fields': ('author', 'status', 'ai_generator', 'source_credit', 'source_credit_url', 'order'),
        }),
        ('Moderation', {
            'fields': (
                'moderation_status', 'requires_manual_review', 'needs_seo_review',
                'moderation_completed_at', 'reviewed_by', 'review_notes',
            ),
            'description': 'AI moderation status and manual review',
        }),
        ('Soft Delete', {
            'fields': ('deleted_at', 'deleted_by', 'deletion_reason', 'original_status'),
            'description': '🚨 Managed by the trash system. Edit with extreme caution.',
        }),
        ('Processing Status', {
            'fields': ('processing_uuid', 'processing_complete', 'seo_pass2_at'),
            'description': 'Background processing status for optimistic upload flow',
        }),
        ('Timestamps', {
            'fields': ('created_on', 'updated_on'),
            'description': 'Automatically managed timestamps',
        }),
    )

    readonly_fields = (
        'id',
        'b2_image_url', 'b2_thumb_url', 'b2_medium_url', 'b2_large_url',
        'b2_webp_url', 'b2_video_url', 'b2_video_thumb_url',
        'video_width', 'video_height',
        'created_on', 'updated_on', 'moderation_completed_at', 'media_preview_display',
        'processing_uuid', 'processing_complete', 'seo_pass2_at',
        'deleted_at', 'deleted_by', 'deletion_reason',
    )

    def change_view(self, request, object_id, form_url='', extra_context=None):
        extra_context = extra_context or {}
        if request.user.is_superuser:
            extra_context['show_regenerate_button'] = True
            extra_context['regenerate_url'] = reverse(
                'admin:prompts_prompt_regenerate', args=[object_id],
            )
            # SEO Review button — only for published prompts
            try:
                prompt = Prompt.objects.only('status').get(pk=object_id)
                if prompt.status == 1:
                    extra_context['show_seo_review_button'] = True
                    extra_context['seo_review_url'] = reverse(
                        'admin:prompts_prompt_seo_review', args=[object_id],
                    )
            except Prompt.DoesNotExist:
                pass
        return super().change_view(request, object_id, form_url, extra_context)

    def get_form(self, request, obj=None, **kwargs):
        form = super().get_form(request, obj, **kwargs)
        if 'title' in form.base_fields:
            form.base_fields['title'].help_text = (
                '📏 <strong>10-80 characters recommended.</strong><br>'
                'Titles appear in Google results (truncated at ~60 chars), '
                'OG/Twitter cards, and browser tabs.<br>'
                '⚠️ Changing the title does NOT update the stored B2 filename or alt tag.'
            )
        # slug help_text is set in PromptAdminForm.__init__ (with widget attrs)
        if 'excerpt' in form.base_fields:
            form.base_fields['excerpt'].help_text = (
                '📄 <strong>AI-generated description for SEO.</strong><br>'
                '150-300 words recommended. Max 2000 characters.<br>'
                '🔍 Used in: meta description, OG cards, search result snippets.'
            )
        if 'categories' in form.base_fields:
            form.base_fields['categories'].help_text = (
                '📂 <strong>1-5 categories recommended.</strong><br>'
                f'📊 Categories = {int(W_CATEGORY * 100)}% of related prompts score.<br>'
                f'🚨 0 categories = algorithm loses {int(W_CATEGORY * 100)}% matching signal.'
            )
        if 'descriptors' in form.base_fields:
            form.base_fields['descriptors'].help_text = (
                '🏷️ <strong>4-8 descriptors recommended.</strong><br>'
                'Should span multiple types: gender, ethnicity, mood, color, setting.<br>'
                f'📊 Descriptors = {int(W_DESCRIPTOR * 100)}% of related prompts score — the single biggest factor.'
            )
        if 'ai_generator' in form.base_fields:
            form.base_fields['ai_generator'].help_text = (
                '🤖 The AI tool used to create this image/video.<br>'
                f'📊 {int(W_GENERATOR * 100)}% of related prompts score.<br>'
                '⚠️ Changing this does NOT update the stored B2 filename.'
            )
        return form

    def formfield_for_manytomany(self, db_field, request, **kwargs):
        if db_field.name == 'tags':
            kwargs['help_text'] = (
                '🏷️ <strong>Up to 10 tags.</strong><br>'
                f'📊 Tags = {int(W_TAG * 100)}% of related prompts score.<br>'
                '💡 New tags auto-created if typed manually.'
            )
        return super().formfield_for_manytomany(db_field, request, **kwargs)

    def get_queryset(self, request):
        """Optimize queries with select_related and prefetch_related"""
        qs = super().get_queryset(request)
        return qs.select_related(
            'author', 'deleted_by', 'reviewed_by'
        ).prefetch_related('tags', 'likes')

    def tag_list(self, obj):
        return ", ".join(o.name for o in obj.tags.all())
    tag_list.short_description = 'Tags'

    def category_count(self, obj):
        return obj.categories.count()
    category_count.short_description = 'Cats'

    def descriptor_count(self, obj):
        return obj.descriptors.count()
    descriptor_count.short_description = 'Descs'

    def media_preview_display(self, obj):
        """Display image/video preview using B2 CDN URLs with fallbacks."""
        if obj.is_video():
            thumb_url = obj.b2_video_thumb_url or obj.display_thumb_url
            if thumb_url:
                return format_html(
                    '<div style="margin: 10px 0;">'
                    '<p><strong>Video Thumbnail:</strong></p>'
                    '<img src="{}" style="max-width: 950px; height: auto; border: 1px solid #ddd; border-radius: 4px;" />'
                    '<p style="margin-top: 5px; color: #666; font-size: 12px;">Duration: {} seconds</p>'
                    '</div>',
                    thumb_url, obj.video_duration or "Unknown"
                )
        else:
            image_url = obj.b2_large_url or obj.display_large_url
            if not image_url and obj.featured_image:
                try:
                    image_url = obj.featured_image.url
                except Exception:
                    pass  # nosec B110 — featured_image may not exist or have no file
            if image_url:
                return format_html(
                    '<div style="margin: 10px 0;">'
                    '<p><strong>Image Preview:</strong></p>'
                    '<img src="{}" style="max-width: 950px; height: auto; border: 1px solid #ddd; border-radius: 4px;" />'
                    '</div>',
                    image_url
                )

        return format_html(
            '<p style="color: #999; font-style: italic;">No image or video</p>'
        )
    media_preview_display.short_description = 'Media Preview'

    def image_validation(self, obj):
        """Check if Cloudinary image/video is valid and accessible"""
        if not obj.featured_image and not obj.featured_video:
            return format_html(
                '<span style="color: #999;">No media</span>'
            )

        try:
            # Try to get the URL - if Cloudinary resource is broken, this will fail
            if obj.featured_image:
                url = obj.featured_image.url
                public_id = obj.featured_image.public_id
                icon = '✓'
                color = '#28a745'  # green
                title = f'Valid image: {public_id}'
            elif obj.featured_video:
                url = obj.featured_video.url
                public_id = obj.featured_video.public_id
                icon = '✓'
                color = '#28a745'  # green
                title = f'Valid video: {public_id}'

            return format_html(
                '<span style="color: {}; font-weight: bold;" title="{}">{}</span>',
                color, title, icon
            )
        except Exception as e:
            # If we can't access the URL, the Cloudinary resource is broken
            return format_html(
                '<span style="color: #dc3545; font-weight: bold;" title="Error: {}">✗ BROKEN</span>',
                str(e)
            )
    image_validation.short_description = 'Media Valid?'

    def moderation_badge(self, obj):
        """Display moderation status with color-coded badge"""
        colors = {
            'approved': '#28a745',  # green
            'rejected': '#dc3545',  # red
            'flagged': '#ffc107',   # yellow
            'pending': '#6c757d',   # grey
        }
        icons = {
            'approved': '✓',
            'rejected': '✗',
            'flagged': '⚠',
            'pending': '⏳',
        }
        color = colors.get(obj.moderation_status, '#6c757d')
        icon = icons.get(obj.moderation_status, '?')
        review_flag = ' 🔍' if obj.requires_manual_review else ''

        return format_html(
            '<span style="background-color: {}; color: white; padding: 3px 8px; '
            'border-radius: 3px; font-weight: bold;">{} {}</span>{}',
            color, icon, obj.get_moderation_status_display(), review_flag
        )
    moderation_badge.short_description = 'Moderation'
    moderation_badge.admin_order_field = 'moderation_status'

    def media_type(self, obj):
        """Display whether the prompt contains an image or video"""
        if obj.is_video():
            return '🎥 Video'
        return '🖼️ Image'
    media_type.short_description = 'Type'

    def reorder_links(self, obj):
        """Provide up/down arrows for quick reordering"""
        if obj.pk:
            move_up_url = reverse('admin:prompts_prompt_move_up', args=[obj.pk])
            move_down_url = reverse('admin:prompts_prompt_move_down', args=[obj.pk])
            return format_html(
                '<a href="{}" title="Move Up">↑</a> | <a href="{}" title="Move Down">↓</a>',
                move_up_url, move_down_url
            )
        return "Save first"
    reorder_links.short_description = 'Move'
    reorder_links.allow_tags = True

    def make_published(self, request, queryset):
        """
        Simple publish action - ONLY sets status=1.
        WARNING: Does NOT clear moderation flags.
        """
        # Count flagged prompts that need proper approval
        flagged_count = queryset.filter(
            moderation_status='flagged',
            requires_manual_review=True
        ).count()

        # Warn admin if flagged prompts detected
        if flagged_count > 0:
            from django.contrib import messages
            self.message_user(
                request,
                f'⚠️ WARNING: {flagged_count} prompt(s) still have moderation flags. '
                f'Users will NOT be able to toggle draft/publish on these prompts. '
                f'Use "Approve & Publish" action instead to clear moderation flags.',
                level=messages.WARNING
            )

        # Proceed with simple publish
        updated = queryset.update(status=1)
        self.message_user(
            request,
            f'{updated} prompt{"s" if updated != 1 else ""} published (status only).'
        )
    make_published.short_description = 'Publish (status only - does NOT clear moderation flags)'

    def make_draft(self, request, queryset):
        """Mark prompts as drafts. Does NOT change moderation status."""
        updated = queryset.update(status=0)
        self.message_user(
            request,
            f'{updated} prompt{"s" if updated != 1 else ""} moved to draft.'
        )
    make_draft.short_description = 'Move to Draft'

    def approve_and_publish(self, request, queryset):
        """
        Approve moderation AND publish prompts.
        This clears moderation flags and allows users to toggle draft/publish.
        """
        # Count how many actually need approval
        needs_approval = queryset.filter(
            moderation_status__in=['flagged', 'pending'],
            requires_manual_review=True
        ).count()

        # Update ALL selected prompts
        updated = queryset.update(
            status=1,
            moderation_status='approved',
            requires_manual_review=False
        )

        # Informative success message
        if needs_approval > 0:
            self.message_user(
                request,
                f'✓ {updated} prompts approved and published. '
                f'{needs_approval} flagged prompt(s) now cleared - users can toggle draft/publish.'
            )
        else:
            self.message_user(
                request,
                f'✓ {updated} prompts approved and published.'
            )
    approve_and_publish.short_description = 'Approve & Publish (clears moderation flags)'

    def reset_order_to_date(self, request, queryset):
        """Reset order based on creation date (newest first)"""
        prompts = list(queryset.order_by('-created_on'))
        for index, prompt in enumerate(prompts):
            prompt.order = index
            prompt.save(update_fields=['order'])

        self.message_user(
            request,
            f'Reset order for {len(prompts)} prompts based on creation date.'
        )
    reset_order_to_date.short_description = 'Reset order to creation date'

    @staticmethod
    def _get_prompt_image_url(prompt):
        """Get the best available image URL for AI analysis."""
        image_url = prompt.b2_image_url or prompt.b2_video_thumb_url
        if not image_url and prompt.featured_image:
            try:
                image_url = prompt.featured_image.url
            except Exception:
                pass  # nosec B110 — featured_image may not exist or have no file
        return image_url

    @staticmethod
    def _apply_ai_m2m_updates(prompt, ai_result, all_categories, all_descriptors):
        """Apply tags, categories, and descriptors from AI result to prompt."""
        from taggit.models import Tag as TagModel

        tags = ai_result.get('tags', [])
        if tags:
            from prompts.tasks import _validate_and_fix_tags
            clean_tags = _validate_and_fix_tags(tags, prompt_id=prompt.pk)
            if clean_tags:
                prompt.tags.clear()
                for tag_name in clean_tags:
                    if tag_name:
                        tag_obj, _ = TagModel.objects.get_or_create(name=tag_name)
                        prompt.tags.add(tag_obj)

        categories = ai_result.get('categories', [])
        if categories:
            matched = [
                all_categories[str(c).strip()]
                for c in categories[:5]
                if str(c).strip() in all_categories
            ]
            if matched:
                prompt.categories.set(matched)

        descriptors_dict = ai_result.get('descriptors', {})
        if descriptors_dict and isinstance(descriptors_dict, dict):
            all_names = []
            for vals in descriptors_dict.values():
                if isinstance(vals, list):
                    all_names.extend(str(v).strip() for v in vals if v)
            matched = [all_descriptors[n] for n in all_names if n in all_descriptors]
            if matched:
                prompt.descriptors.set(matched)

    def run_seo_review(self, request, queryset):
        """
        Admin action: Run Pass 2 SEO review on selected prompts.

        This ONLY optimizes existing tags and description — it does NOT
        regenerate title, categories, or descriptors. Use this when the
        current content is good but tags could be better.

        Only works on published prompts (drafts are skipped).
        """
        from prompts.tasks import queue_pass2_review

        queued = 0
        skipped_draft = 0
        skipped_recent = 0

        for prompt in queryset:
            if prompt.status != 1:
                skipped_draft += 1
                continue

            result = queue_pass2_review(prompt.pk)
            if result:
                queued += 1
            else:
                skipped_recent += 1

        parts = []
        if queued:
            parts.append(
                f'✅ Queued SEO review for {queued} prompt(s). '
                f'Tags and descriptions will be optimized in ~45 seconds'
            )
        if skipped_draft:
            parts.append(
                f'⏭️ Skipped {skipped_draft} draft(s) — only published prompts can be reviewed'
            )
        if skipped_recent:
            parts.append(
                f'⏭️ Skipped {skipped_recent} recently-reviewed prompt(s) — reviewed within last 5 minutes'
            )

        message = '. '.join(parts) if parts else 'No prompts selected.'
        self.message_user(request, message)
    run_seo_review.short_description = (
        '🎯 Optimize Tags & Description (Pass 2)'
    )

    def regenerate_ai_content(self, request, queryset):
        """Re-run AI content generation for selected prompts."""
        if not request.user.is_superuser:
            self.message_user(
                request,
                '🚫 Only superusers can regenerate AI content (API cost control).',
                level='error'
            )
            return

        from taggit.models import Tag as TagModel
        from prompts.tasks import _call_openai_vision, _sanitize_content
        from prompts.models import SubjectCategory, SubjectDescriptor
        from django.db import transaction

        count = queryset.count()
        if count > 10:
            self.message_user(
                request,
                f'🚫 {count} prompts selected — max 10 for inline regeneration. '
                f'💡 Use: python manage.py backfill_ai_content --limit {count}',
                level='warning'
            )
            return

        available_tags = list(TagModel.objects.values_list('name', flat=True)[:200])
        all_categories = {c.name: c for c in SubjectCategory.objects.all()}
        all_descriptors = {d.name: d for d in SubjectDescriptor.objects.all()}

        success = 0
        errors = []
        for prompt in queryset:
            image_url = self._get_prompt_image_url(prompt)
            if not image_url:
                errors.append(f'{prompt.title[:30]}: No image URL')
                continue
            try:
                ai_result = _call_openai_vision(
                    image_url=image_url,
                    prompt_text=prompt.content[:500] if prompt.content else '',
                    ai_generator=(
                        prompt.get_ai_generator_display()
                        if hasattr(prompt, 'get_ai_generator_display')
                        else 'AI'
                    ),
                    available_tags=available_tags,
                )
                if ai_result.get('error'):
                    errors.append(f'{prompt.title[:30]}: {ai_result["error"][:50]}')
                    continue

                title = _sanitize_content(
                    ai_result.get('title') or f'AI Artwork #{prompt.pk}',
                    max_length=200,
                )
                description = _sanitize_content(
                    ai_result.get('description', ''), max_length=2000,
                )

                with transaction.atomic():
                    # Slug protection: preserve current slug during regeneration
                    prompt.title = title
                    prompt.excerpt = description
                    prompt.save(update_fields=['title', 'excerpt'])

                    self._apply_ai_m2m_updates(
                        prompt, ai_result, all_categories, all_descriptors,
                    )
                success += 1
                # Queue Pass 2 SEO review for published prompts
                if prompt.status == 1:
                    from prompts.tasks import queue_pass2_review
                    queue_pass2_review(prompt.pk)
            except Exception as e:
                errors.append(f'{prompt.title[:30]}: {str(e)[:50]}')

        pass2_note = ''
        published_count = queryset.filter(status=1).count()
        pass2_note = ''
        if published_count:
            pass2_note = (
                ' SEO optimization of tags will follow automatically in ~45 seconds.'
            )

        if errors:
            self.message_user(
                request,
                f'⚠️ Regenerated {success}/{count}.{pass2_note} Errors: {"; ".join(errors)}',
                level='warning'
            )
        else:
            self.message_user(
                request,
                f'✅ Regenerated AI content for {success} prompt(s).{pass2_note}'
            )
    regenerate_ai_content.short_description = (
        '🔄 Rebuild All Content (Pass 1 + 2)'
    )

    def get_urls(self):
        """Add custom URLs for move up/down and regenerate actions."""
        from django.urls import path
        urls = super().get_urls()
        custom_urls = [
            path(
                '<int:pk>/move-up/',
                self.admin_site.admin_view(self.move_up_view),
                name='prompts_prompt_move_up',
            ),
            path(
                '<int:pk>/move-down/',
                self.admin_site.admin_view(self.move_down_view),
                name='prompts_prompt_move_down',
            ),
            path(
                '<int:pk>/regenerate/',
                self.admin_site.admin_view(self.regenerate_view),
                name='prompts_prompt_regenerate',
            ),
            path(
                '<int:pk>/seo-review/',
                self.admin_site.admin_view(self.seo_review_view),
                name='prompts_prompt_seo_review',
            ),
        ]
        return custom_urls + urls

    def move_up_view(self, request, pk):
        """Move prompt up in order (decrease order number)"""
        from django.shortcuts import get_object_or_404, redirect
        from django.contrib import messages
        from django.core.cache import cache

        prompt = get_object_or_404(Prompt, pk=pk)

        # Find the prompt with the next lower order number
        previous_prompt = Prompt.objects.filter(
            order__lt=prompt.order
        ).order_by('-order').first()

        if previous_prompt:
            # Swap the order values
            prompt.order, previous_prompt.order = previous_prompt.order, prompt.order
            prompt.save(update_fields=['order'])
            previous_prompt.save(update_fields=['order'])

            # Clear all relevant caches
            self.clear_prompt_caches()

            messages.success(request, f'Moved "{prompt.title}" up.')
        else:
            messages.warning(request, f'"{prompt.title}" is already at the top.')

        return redirect('admin:prompts_prompt_changelist')

    def move_down_view(self, request, pk):
        """Move prompt down in order (increase order number)"""
        from django.shortcuts import get_object_or_404, redirect
        from django.contrib import messages
        from django.core.cache import cache

        prompt = get_object_or_404(Prompt, pk=pk)

        # Find the prompt with the next higher order number
        next_prompt = Prompt.objects.filter(
            order__gt=prompt.order
        ).order_by('order').first()

        if next_prompt:
            # Swap the order values
            prompt.order, next_prompt.order = next_prompt.order, prompt.order
            prompt.save(update_fields=['order'])
            next_prompt.save(update_fields=['order'])

            # Clear all relevant caches
            self.clear_prompt_caches()

            messages.success(request, f'Moved "{prompt.title}" down.')
        else:
            messages.warning(request, f'"{prompt.title}" is already at the bottom.')

        return redirect('admin:prompts_prompt_changelist')

    def regenerate_view(self, request, pk):
        """Regenerate AI content for a single prompt with confirmation page."""
        from django.shortcuts import get_object_or_404, redirect
        from django.contrib import messages
        from django.template.response import TemplateResponse

        if not request.user.is_superuser:
            messages.error(request, '🚫 Only superusers can regenerate AI content.')
            return redirect('admin:prompts_prompt_changelist')

        prompt = get_object_or_404(Prompt, pk=pk)

        if request.method == 'GET':
            context = {
                **self.admin_site.each_context(request),
                'prompt': prompt,
                'title': f'Regenerate AI Content: {prompt.title}',
                'opts': self.model._meta,
            }
            return TemplateResponse(
                request,
                'admin/prompts/prompt/regenerate_confirm.html',
                context,
            )

        # POST — execute regeneration
        from taggit.models import Tag as TagModel
        from prompts.tasks import (
            _call_openai_vision, _sanitize_content,
        )
        from prompts.models import SubjectCategory, SubjectDescriptor
        from django.db import transaction

        image_url = self._get_prompt_image_url(prompt)
        if not image_url:
            messages.error(request, f'No image URL found for "{prompt.title}".')
            return redirect('admin:prompts_prompt_change', pk)

        available_tags = list(TagModel.objects.values_list('name', flat=True)[:200])
        all_categories = {c.name: c for c in SubjectCategory.objects.all()}
        all_descriptors = {d.name: d for d in SubjectDescriptor.objects.all()}

        try:
            ai_result = _call_openai_vision(
                image_url=image_url,
                prompt_text=prompt.content[:500] if prompt.content else '',
                ai_generator=(
                    prompt.get_ai_generator_display()
                    if hasattr(prompt, 'get_ai_generator_display')
                    else 'AI'
                ),
                available_tags=available_tags,
            )
            if ai_result.get('error'):
                messages.error(
                    request, f'AI error: {str(ai_result["error"])[:200]}'
                )
                return redirect('admin:prompts_prompt_change', pk)

            title = _sanitize_content(
                ai_result.get('title') or f'AI Artwork #{prompt.pk}',
                max_length=200,
            )
            description = _sanitize_content(
                ai_result.get('description', ''), max_length=2000,
            )

            with transaction.atomic():
                # Slug protection: preserve current slug during regeneration
                prompt.title = title
                prompt.excerpt = description
                prompt.save(update_fields=['title', 'excerpt'])

                self._apply_ai_m2m_updates(
                    prompt, ai_result, all_categories, all_descriptors,
                )

            # Queue Pass 2 SEO review for published prompts
            if prompt.status == 1:
                from prompts.tasks import queue_pass2_review
                queue_pass2_review(prompt.pk)
                messages.success(
                    request,
                    f'🔄 All content rebuilt for "{title}". '
                    f'Tag optimization will follow automatically in ~45 seconds. '
                    f'Refresh the page after a minute to see final improvements.',
                )
            else:
                messages.success(
                    request,
                    f'🔄 All content rebuilt for "{title}". '
                    f'Title and description updated (slug preserved: {prompt.slug}).',
                )
        except Exception as e:
            logger.exception('Regeneration failed for prompt pk=%s', pk)
            messages.error(request, f'Regeneration failed: {str(e)[:100]}')

        return redirect('admin:prompts_prompt_change', pk)

    def seo_review_view(self, request, pk):
        """Individual prompt page: Run Pass 2 SEO review only (POST only)."""
        from django.shortcuts import get_object_or_404, redirect
        from django.contrib import messages
        from prompts.tasks import queue_pass2_review

        if request.method != 'POST':
            return redirect('admin:prompts_prompt_change', pk)

        if not request.user.is_superuser:
            messages.error(
                request,
                '⛔ Only superusers can run SEO reviews.',
            )
            return redirect('admin:prompts_prompt_changelist')

        prompt = get_object_or_404(Prompt, pk=pk)

        if prompt.status != 1:
            messages.warning(
                request,
                f'⚠️ SEO Review skipped — "{prompt.title}" is a draft. '
                f'Publish the prompt first, then run SEO Review.',
            )
            return redirect('admin:prompts_prompt_change', pk)

        result = queue_pass2_review(prompt.pk)

        if result:
            messages.success(
                request,
                f'🎯 Tags & description optimization queued for "{prompt.title}". '
                f'Results apply in ~45 seconds. '
                f'Refresh the page after a minute to see changes.',
            )
        else:
            messages.info(
                request,
                f'⏭️ SEO Review skipped — "{prompt.title}" was already reviewed '
                f'within the last 5 minutes. Wait a bit and try again.',
            )

        return redirect('admin:prompts_prompt_change', pk)

    def clear_prompt_caches(self):
        """Clear all prompt-related caches"""
        from django.core.cache import cache

        # Clear list caches for multiple pages and tags
        for page in range(1, 10):  # Clear more pages
            cache.delete(f"prompt_list_None_None_{page}")
            # Clear tag-filtered caches too
            for tag in ['art', 'portrait', 'landscape', 'photography']:  # Add your common tags
                cache.delete(f"prompt_list_{tag}_None_{page}")

        # Clear individual prompt detail caches
        prompts = Prompt.objects.all()[:50]  # Clear recent prompts
        for prompt in prompts:
            cache.delete(f"prompt_detail_{prompt.slug}_anonymous")
            # Clear user-specific caches (this is imperfect, but helps)
            for user_id in range(1, 20):  # Adjust range based on your user count
                cache.delete(f"prompt_detail_{prompt.slug}_{user_id}")

    def save_model(self, request, obj, form, change):
        """Create slug redirect on slug change + title warnings + cache clearing.

        Slug validation (format, reserved, uniqueness) is handled by
        PromptAdminForm.clean_slug() — errors show inline on the form field.
        """
        from django.db import transaction

        # Capture old slug before save (must read from DB before transaction)
        old_slug = None
        new_slug = None
        slug_changed = False

        if change and 'slug' in form.changed_data:
            old_prompt = Prompt.all_objects.get(pk=obj.pk)
            old_slug = old_prompt.slug
            new_slug = obj.slug
            slug_changed = old_slug != new_slug

        # Title length warnings (non-blocking, outside transaction)
        if obj.title:
            title_len = len(obj.title)
            if title_len > 80:
                self.message_user(
                    request,
                    f'⚠️ Title is {title_len} chars (recommended: 10-80 for SEO).',
                    level='warning'
                )
            elif title_len < 10:
                self.message_user(
                    request,
                    f'⚠️ Title is only {title_len} chars (recommended: 10-80 for SEO).',
                    level='warning'
                )

        # Atomic: both prompt save and redirect creation succeed or both roll back
        with transaction.atomic():
            super().save_model(request, obj, form, change)

            if slug_changed:
                # Prevent circular redirects
                SlugRedirect.objects.filter(old_slug=new_slug).delete()
                # Create or update redirect for old slug
                SlugRedirect.objects.update_or_create(
                    old_slug=old_slug,
                    defaults={'prompt': obj}
                )

        # Messages after successful commit
        if slug_changed:
            self.message_user(
                request,
                f'✅ Slug changed: "{old_slug}" → "{new_slug}". '
                f'🔗 301 redirect created automatically.',
                level='success'
            )

        if change and 'order' in form.changed_data:
            self.clear_prompt_caches()

        # Queue SEO file rename if B2 image is present.
        # Mirrors the guard in upload_views.py — applies to both new and edited prompts.
        if obj.b2_image_url:
            from django_q.tasks import async_task
            try:
                async_task(
                    'prompts.tasks.rename_prompt_files_for_seo',
                    obj.pk,
                    task_name=f'seo-rename-{obj.pk}',
                )
                logger.info(f'Admin save_model: queued SEO rename for prompt {obj.pk}')
            except Exception as e:
                # Non-blocking: rename failure shouldn't break the admin save
                logger.warning(f'Admin save_model: failed to queue SEO rename for prompt {obj.pk}: {e}')

    def save_related(self, request, form, formsets, change):
        """M2M validation warnings after save."""
        super().save_related(request, form, formsets, change)
        obj = form.instance

        cat_count = obj.categories.count()
        if cat_count == 0:
            self.message_user(
                request,
                '⚠️ No categories assigned. '
                f'📊 Related prompts algorithm loses {int(W_CATEGORY * 100)}% signal.',
                level='warning'
            )
        elif cat_count > 5:
            self.message_user(
                request,
                f'⚠️ {cat_count} categories assigned (recommended max: 5).',
                level='warning'
            )

        desc_count = obj.descriptors.count()
        if desc_count == 0:
            self.message_user(
                request,
                '🚨 No descriptors assigned. '
                f'📊 Descriptors = {int(W_DESCRIPTOR * 100)}% of related prompts score.',
                level='warning'
            )
        elif desc_count > 10:
            self.message_user(
                request,
                f'⚠️ {desc_count} descriptors assigned (recommended: 4-8).',
                level='warning'
            )

        tag_count = obj.tags.count()
        if tag_count == 0:
            self.message_user(
                request,
                '🚨 No tags assigned. '
                f'📊 Tags = {int(W_TAG * 100)}% of related prompts score.',
                level='warning'
            )
        elif tag_count > 10:
            self.message_user(
                request,
                f'⚠️ {tag_count} tags assigned (max recommended: 10).',
                level='warning'
            )


@admin.register(PromptView)
class PromptViewAdmin(admin.ModelAdmin):
    """Admin interface for viewing prompt views (read-only analytics)."""
    list_display = ('prompt', 'user', 'session_display', 'viewed_at')
    list_filter = ('viewed_at',)
    search_fields = ('prompt__title', 'user__username')
    readonly_fields = ('prompt', 'user', 'session_key', 'ip_hash', 'viewed_at')
    ordering = ('-viewed_at',)
    date_hierarchy = 'viewed_at'

    def session_display(self, obj):
        """Display truncated session key for anonymous users."""
        if obj.user:
            return '-'  # User is identified
        return obj.session_key[:8] + '...' if obj.session_key else '-'
    session_display.short_description = 'Session'

    def has_add_permission(self, request):
        # Views are recorded automatically, not manually added
        return False

    def has_change_permission(self, request, obj=None):
        # Views should be read-only
        return False


@admin.register(SlugRedirect)
class SlugRedirectAdmin(admin.ModelAdmin):
    list_display = ('old_slug', 'prompt', 'created_at')
    search_fields = ('old_slug', 'prompt__title')
    list_filter = ('created_at',)
    readonly_fields = ('created_at',)
    raw_id_fields = ('prompt',)

    def has_add_permission(self, request):
        return request.user.is_superuser

    def has_change_permission(self, request, obj=None):
        return request.user.is_superuser

    def has_delete_permission(self, request, obj=None):
        return request.user.is_superuser
